##################################################
#配置数据源和数据连接池
##################################################
spring:
  datasource: #数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource #数据源类型
    #SpringBoot2.0内置jdbc5驱动：com.mysql.jdbc.Driver，SpringBoot2.1及其以上版本内置jdbc8驱动：com.mysql.cj.jdbc.Driver
    #使用MySql 6及以上必须同时需要指定时区serverTimezone，serverTimezone=GMT%2B8，指指定时区为北京时间==东八区时间
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-dev?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: zY199546!
    hikari: #hikari 配置相关
      connection-timeout:  30000 #等待连接池分配连接的最大时长（毫秒），超过这个时长还没有可用连接则发生SQLException,默认30秒
      minimum-idle: 5 #最小连接数  dev环境一般设置5，生产环境设置10
      maximum-pool-size: 20 #最大连接数(默认10，具体值不是越大越好，而是根据服务器配置进行设置)
      auto-commit: true #自动提交
      idle-timeout: 600000 #连接超时的最大时长（毫秒），超时则被释放（retired),默认10分钟
      pool-name: DataSourceHikariCP #连接池名称
      max-lifetime: 1800000 #连接的生命时长（毫秒），超时而且没被使用则被释放，默认30分钟
      connection-test-query: SELECT 1

##################################################
#mybatis 配置
##################################################

mybatis:
  type-aliases-package: com.imooc.pojo
  mapper-locations: classpath:mapper/*.xml


##################################################
#内置tomcat web访问端口约定：8088
##################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

##################################################
# mybatis mapper 配置
##################################################
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
